services:
  clicker_mania:
    image: clicker_mania:latest
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - 3000:3306
    volumes:
      - ./:/docker_app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - $HOME/.aws/config:/root/.aws/config:ro
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_DB: clicker_mania
    depends_on:
      - mysql


  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etcmysql
      - ./src/utils/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=example

#  grafana:
#    image: grafana/grafana:7.5.7
#    ports:
#      - 3000:3000
#    restart: unless-stopped
#    volumes:
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#      - grafana-data:/var/lib/grafana


volumes:
  mysql_data:
  mysql_config:
#  grafana-data: